import express from "express";
import dotenv from "dotenv";
import SigupRoute from "./Routes/signup.routes.js";
import LoginRoute from "./Routes/login.routes.js";
import PaymentIntentRoute from "./Routes/paymentintent.routes.js";
import cors from "cors";
dotenv.config();
import ConnectdB from "./Db/db.conn.js";
import PaymentConfigRoute from "./Routes/paymentconfig.routes.js";
import userDetailsRoute from "./Routes/userdetails.routes.js";
import editProfileRoute from "./Routes/editprofile.routes.js";
import userContactRoute from "./Routes/usercontact.routes.js";
import addressBookRoute from "./Routes/addressbook.routes.js";
import getAddressRoute from "./Routes/getaddressbook.routes.js";
import deleteAddressBookRoute from "./Routes/deleteaddressbook.routes.js";
import editAddressBookRoute from "./Routes/editaddressbook.routes.js";
import paymentOptionRoute from "./Routes/paymentoption.routes.js";
import editPaymentOptionRoute from "./Routes/editpaymentoption.routes.js";
import getPaymentOptionRoute from "./Routes/getpaymentoption.routes.js";
import deletePaymentOptionRoute from "./Routes/deletepaymentoption.routes.js";
import cancellatinRoute from "./Routes/cancellation.routes.js";
import getCancellationRoute from "./Routes/getcancellation.routes.js";
import editCancellationRoute from "./Routes/editcancellation.routes.js";
import deleteCancellationRoute from "./Routes/deletecancellation.routes.js";
import returnRoute from "./Routes/return.routes.js";
import getReturnRoute from "./Routes/getreturn.routes.js";
import editReturnRoute from "./Routes/editreturn.routes.js";
import deleteReturnRoute from "./Routes/deletereturn.routes.js";
const app = express();
app.use(cors());
app.use(express.json());
app.use("/api", SigupRoute);
app.use("/api", LoginRoute);
app.use("/api", PaymentIntentRoute);
app.use("/api", PaymentConfigRoute);
app.use("/api", userDetailsRoute);
app.use("/api", editProfileRoute);
app.use("/api", userContactRoute);
app.use("/api", addressBookRoute);
app.use("/api", getAddressRoute);
app.use("/api", deleteAddressBookRoute);
app.use("/api", editAddressBookRoute);
app.use("/api", paymentOptionRoute);
app.use("/api", editPaymentOptionRoute);
app.use("/api", getPaymentOptionRoute);
app.use("/api", deletePaymentOptionRoute);
app.use("/api", cancellatinRoute);
app.use("/api", getCancellationRoute);
app.use("/api", editCancellationRoute);
app.use("/api", deleteCancellationRoute);
app.use("/api", returnRoute);
app.use("/api",getReturnRoute);
app.use("/api",editReturnRoute);
app.use("/api",deleteReturnRoute);

ConnectdB().then(() => {
  app.listen(process.env.PORT || 2010, () => {
    console.log(`Listening to port ${process.env.PORT}:`);
  });
});
